import os
import json
import time
import subprocess
from flask import Flask, request, jsonify
from google import genai
from google.genai import types

app = Flask(__name__)

# --- SRE TOOLS (Functions the AI Agent can execute dynamically) ---

def fetch_pod_logs(pod_name: str, namespace: str = "default") -> str:
    """Executes 'kubectl logs' to grab stdout/stderr from a failing pod."""
    try:
        cmd = ["kubectl", "logs", pod_name, "-n", namespace, "--tail=100"]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        return result.stdout if result.stdout else "No log output available."
    except subprocess.CalledProcessError as e:
        return f"Failed to get logs for pod {pod_name}: {e.stderr}"

def fetch_pod_description(pod_name: str, namespace: str = "default") -> str:
    """Executes 'kubectl describe pod' to view events, lifecycle states, or OOMKilled status."""
    try:
        cmd = ["kubectl", "describe", "pod", pod_name, "-n", namespace]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        return result.stdout
    except subprocess.CalledProcessError as e:
        return f"Failed to describe pod {pod_name}: {e.stderr}"


# --- WEBHOOK ENDPOINT (Listens to Prometheus Alertmanager) ---

@app.route('/webhook', methods=['POST'])
def alert_webhook():
    alert_data = request.json
    print("🚨 Alert received from Alertmanager!")
    
    try:
        alert = alert_data.get('alerts', [{}])[0]
        labels = alert.get('labels', {})
        pod_name = labels.get('pod') or labels.get('kubernetes_pod_name')
        alert_name = labels.get('alertname', 'UnknownClusterAnomaly')
        namespace = labels.get('namespace', 'default')
    except Exception:
        return jsonify({"status": "ignored", "reason": "invalid alert structure"}), 400

    if not pod_name:
        print("⚠️ Alert omitted: No specific pod name linked to this metric event.")
        return jsonify({"status": "ignored", "reason": "no target pod discovered"}), 200

    print(f"🔍 Analyzing incident room for Pod: '{pod_name}' due to Alert: '{alert_name}'...")

    client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

    available_tools = {
        "fetch_pod_logs": fetch_pod_logs,
        "fetch_pod_description": fetch_pod_description
    }

    system_instruction = """
    You are an autonomous Senior Site Reliability Engineer (SRE) Agent tracking a live production failure.
    Your objective is to diagnose cluster anomalies.
    CRITICAL: You are NOT allowed to guess or resolve the alert immediately. 
    You MUST execute at least one tool ('fetch_pod_description' or 'fetch_pod_logs') to gather data from the cluster before writing your final report.
    """

    user_prompt = f"The cluster triggered an alert '{alert_name}' for pod '{pod_name}' in namespace '{namespace}'. Investigate it now."

    # --- TURN 1: Ask model which tool to use (With Retry Logic for 503 mitigation) ---
    response = None
    max_retries = 3
    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=user_prompt,
                config=types.GenerateContentConfig(
                    system_instruction=system_instruction,
                    tools=[fetch_pod_logs, fetch_pod_description]
                )
            )
            break
        except Exception as e:
            if "503" in str(e) and attempt < max_retries - 1:
                print(f"⚠️ Gemini API overload (503) on Turn 1. Retrying in 6 seconds... ({attempt + 1}/{max_retries})")
                time.sleep(6)
            else:
                print(f"❌ Gemini API completely failed on Turn 1: {e}")
                return jsonify({"status": "failed", "reason": "Gemini API unavailable"}), 503

    # Process function calls generated by the model
    function_calls = response.function_calls
    tool_outputs = []

    if function_calls:
        for call in function_calls:
            tool_name = call.name
            
            print(f"🤖 Agent decided to run tool: {tool_name}")
            
            if tool_name in available_tools:
                tool_func = available_tools[tool_name]
                output_text = tool_func(pod_name=pod_name, namespace=namespace)
                tool_outputs.append({
                    "role": "tool",
                    "name": tool_name,
                    "content": output_text
                })

        # --- TURN 2: Send real data back to get the diagnostic summary ---
        final_response = None
        for attempt in range(max_retries):
            try:
                final_response = client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=[
                        types.Content(role="user", parts=[types.Part.from_text(text=user_prompt)]),
                        response.candidates[0].content,
                        types.Content(role="user", parts=[types.Part.from_text(text=f"Tool output results: {json.dumps(tool_outputs)}")])
                    ],
                    config=types.GenerateContentConfig(system_instruction=system_instruction)
                )
                break
            except Exception as e:
                if "503" in str(e) and attempt < max_retries - 1:
                    print(f"⚠️ Gemini API overload (503) on Turn 2. Retrying in 6 seconds... ({attempt + 1}/{max_retries})")
                    time.sleep(6)
                else:
                    print(f"❌ Gemini API completely failed on Turn 2: {e}")
                    return jsonify({"status": "failed", "reason": "Gemini API unavailable"}), 503
        
        print("\n=================== 🤖 SRE AGENT DIAGNOSTIC REPORT ===================")
        print(final_response.text)
        print("======================================================================\n")
        
    else:
        print("🤖 Agent bypassed tool calling loop:")
        print(response.text)

    return jsonify({"status": "resolved", "agent_triggered": True}), 200

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)